# Generated by Django 5.0 on 2024-01-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='wlist_flag',
            field=models.BooleanField(default=False),
        ),
    ]
