# Generated by Django 5.0 on 2024-01-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_wishlist_wlist_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
