# Generated by Django 4.1.3 on 2024-01-23 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cart',
        ),
    ]
