# Generated by Django 5.0 on 2024-01-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='data',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
